os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_LOGIN_USERNAME: sixten-hilborn
    - CONAN_UPLOAD: https://api.bintray.com/conan/sixten-hilborn/conan
    - CONAN_REFERENCE="RakNet/4.081"
    - CONAN_USERNAME="hilborn"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
matrix:
   include:
   include:
       - os: osx
         osx_image: xcode8.3
         language: generic
         env:
       - os: osx
         osx_image: xcode8
         language: generic
         env:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:ge: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
  
