build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    
    CONAN_LOGIN_USERNAME: sixten-hilborn
    CONAN_UPLOAD: https://api.bintray.com/conan/sixten-hilborn/conan
    CONAN_REFERENCE: "RakNet/4.081"
    CONAN_USERNAME: "hilborn"
    CONAN_CHANNEL: "stable"
    CONAN_TOTAL_PAGES: 6
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    
    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2  
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
        - CONAN_CURRENT_PAGE: 5
        - CONAN_CURRENT_PAGE: 6

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
- python build.py
